FROM golang:alpine AS builder

WORKDIR /build

COPY . .

RUN go mod download \
    && go build -o ./server ./main.go

FROM alpine:latest

WORKDIR /app

RUN mkdir -p /app/templates /app/static

COPY --from=builder /build/server .
COPY ./templates ./templates
COPY ./static ./static
COPY ./.env .

ENTRYPOINT ["./server"]
