name: CI (Contonuous Integration)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build: # job id
    name: Build and Run Container # job name
    runs-on: ubuntu-latest # runner

    steps:
      - uses: actions/checkout@v3
      - name: Make file .env
        run: |
          cd app
          echo "${{secrets.ENV_FILE}}" > .env
      - name: Buil and Run the Docker Image
        run: |
          cd app
          docker compose up -d
  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Download Depedencies
        run: | 
          cd app
          go mod download
      - name: Make file .env
        run: |
          cd app
          echo "${{secrets.ENV_FILE}}" > .env
      - name: Run Test
        run: |
          cd app
          go test -v ./test

